// File generated by manual configuration for Firebase options
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQQIGhLOpsKBy0V2E6Q9bRzNqQ5Ak0Fxo',
    appId: '1:766981626039:web:6f4fda2e967394a44b9532',
    messagingSenderId: '766981626039',
    projectId: 'misericordia-materna-sec',
    authDomain: 'misericordia-materna-sec.firebaseapp.com',
    storageBucket: 'misericordia-materna-sec.firebasestorage.app',
    measurementId: 'G-4ST06Q2XR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdd4l1Byv53Itj2kUNn8aEM38P7JU_WY8',
    appId: '1:766981626039:android:635e1dc8c9c81b494b9532',
    messagingSenderId: '766981626039',
    projectId: 'misericordia-materna-sec',
    storageBucket: 'misericordia-materna-sec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKPS0R8DGGFM-EqGeF-scY9Qr7gXHSjqQ',
    appId: '1:766981626039:ios:0a8fd0cabea8828b4b9532',
    messagingSenderId: '766981626039',
    projectId: 'misericordia-materna-sec',
    storageBucket: 'misericordia-materna-sec.firebasestorage.app',
    iosBundleId: 'br.com.misericordia.materna.appSecretaria',
  );
}
